runtime: python39
service: fe-196
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static
    expiration: "30d"

  - url: /(.*\.(json|txt|xml|ico|png|jpg|jpeg|gif|svg|js|css))$
    static_files: build/\1
    upload: build/(.*\.(json|txt|xml|ico|png|jpg|jpeg|gif|svg|js|css))$
    expiration: "1h"

  - url: /.*
    static_files: build/index.js
    upload: build/index.js

default_expiration: "1h"  # Waktu cache default