steps:

  # Step 1: Build frontend dengan injeksi VITE_API_URL
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        npm run build
    dir: "notes_fe"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "notes_fe"

options:
  logging: CLOUD_LOGGING_ONLY