steps:
  # Step 1: Set Node.js version and install dependencies
  - name: "gcr.io/cloud-builders/nodejs"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Using Node.js 20.x"
        nvm use 20
        if [ ! -d "frontend/node_modules" ]; then
          echo "Installing dependencies..."
          cd frontend
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: Build frontend dengan injeksi VITE_API_URL
  - name: "gcr.io/cloud-builders/nodejs"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Using Node.js 20.x for build"
        nvm use 20
        cd frontend
        npm run build
    env:
      - VITE_API_URL=$VITE_API_URL # Pastikan variabel ini sudah diatur di Cloud Build
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend/dist" # Direktori build React biasanya adalah 'build' atau 'dist'

options:
  logging: CLOUD_LOGGING_ONLY