runtime: nodejs20
service: fe-196  # ganti nama service kalau mau
instance_class: F1

handlers:
  - url: /
    static_files: dist/index.js
    upload: dist/index.js

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)

default_expiration: "1h"